version: '3'
services:
  keycloak:
    image: jboss/keycloak:4.0.0.Final
    container_name: socks-keycloak
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=postgres
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloakdb
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db

  keycloak-db:
      image: postgres:10
      container_name: socks-keycloak-db
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: keycloakdb
      volumes:
        - pgdata:/var/lib/postgresql/data

  postgres:
    image: 'postgres:latest'
    container_name: socks-database
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_DB=socks'
    ports:
      - "5434:5434"
    command: -p 5434

  app:
    build: ./
    container_name: socks-app
    ports:
      - "8080:8080"

volumes:
  pgdata: