spring:
  datasource:
    url: jdbc:postgresql://postgres:5434/socks
    username: postgres
    password: pass
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yml
  messages:
    basename: i18n/messages
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/sock-realm
      client:
        registration:
          keycloak:
            client-id: sock
            client-secret: e769e2f9-e748-4855-b971-f3ebeed702b4
            authorization-grant-type: password
        provider:
          keycloak:
            issuer-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}

keycloak:
  realm: sock-realm
  auth-server-url: http://keycloak:8081/auth
  ssl-required: external
  resource: sock
  credentials.secret: e769e2f9-e748-4855-b971-f3ebeed702b4
  use-resource-role-mappings: true
  bearer-only: true

springdoc:
  packages-to-scan: ru.malletmustdie.cibinternstesttask
  swagger-ui:
    path: /swagger-ui
    oauth:
      clientId: ${spring.security.oauth2.client.registration.keycloak.client-id}
      clientSecret: ${spring.security.oauth2.client.registration.keycloak.client-secret}

mail:
  email: your-mail
  password: your-password
  protocol: smtp
  encoding: utf-8
  debug: true
  smtp:
    name: smtp.gmail.com
    port: 587
    auth: true
    starttlsenable: true