spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/socks
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yml
  messages:
    basename: i18n/messages
  security:
    oauth2:
       client:
         registration:
           google:
             client-id: 519795840998-37dgekgcdcihkgdrp1jvib0kfa7a682v.apps.googleusercontent.com
             client-secret: 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
             scope: openid, profile, email
       resource-server:
         jwt:
           issuer-uri: https://accounts.google.com/o/oauth2/auth
           jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

springdoc:
  packages-to-scan: ru.malletmustdie.cibinternstesttask
  swagger-ui:
    path: /swagger-ui
    oauth:
      client-id: ${spring.security.oauth2.client.registration.google.client-id}
      client-secret: ${spring.security.oauth2.client.registration.google.client-secret}

swagger-security:
  authorization-url: ${spring.security.oauth2.resource-server.jwt.issuer-uri}
  token-url: https://oauth2.googleapis.com/token

mail:
  email: malletapp322@gmail.com
  password: iisqgkxwyfbhlkbt
  protocol: smtp
  encoding: utf-8
  debug: true
  smtp:
    name: smtp.gmail.com
    port: 587
    auth: true
    starttlsenable: true