spring:
  datasource:
    url: jdbc:postgresql://postgres:5434/socks
    username: postgres
    password: pass
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yml
  messages:
    basename: i18n/messages
  security:
    oauth2:
       client:
         registration:
           google:
             client-id: 519795840998-37dgekgcdcihkgdrp1jvib0kfa7a682v.apps.googleusercontent.com
             client-secret: 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
             scope: openid, profile, email
       resource-server:
         jwt:
           issuer-uri: https://accounts.google.com/o/oauth2/auth
           jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

springdoc:
  packages-to-scan: ru.malletmustdie.cibinternstesttask
  swagger-ui:
    path: /swagger-ui
    oauth:
      client-id: ${spring.security.oauth2.client.registration.google.client-id}
      client-secret: ${spring.security.oauth2.client.registration.google.client-secret}

swagger-security:
  authorization-url: ${spring.security.oauth2.resource-server.jwt.issuer-uri}
  token-url: https://oauth2.googleapis.com/token